name	'flask-nginx-webapp'
maintainer	'Asish'
maintainer_email	'asishmm1@gmail.com'
description	'Installs, configures and brings up blog server running Flask on Nginx'
long_description	'This cookbook is responsible for bringing up ec2 instance and install, configure and start server using python / nginx / flask services'
depends 'nginx'
depends 'flask'
depends 'python'
depends 'uwsgi'
